[functions]
  external_node_modules = ["sharp"]
  included_files = ["node_modules/sharp/**/*"]
  
[[plugins]]
    package = "netlify-plugin-bundle-env"
    [plugins.inputs]
    files = ["utils/consts.ts"]
    include = ["DEPLOY_PRIME_URL"]

[functions]
  included_files = ["node_modules/sharp/**/*"]